FROM python:3.8.8-slim-buster

WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY ringConnector ringConnector

ENV OAUTH_FILE=/app/output/oauth-authorization.json


COPY startCreateAuthFile.py .

CMD ./startCreateAuthFile.py