version: "3.9"
services:
  ring-connector:
    build: .
    ports:
      - "5000:5000"
    volumes: 
      - ./data:/app/data
      - ./oauth-autorization.json:/app/oauth-authorization.json
    environment: 
      - OAUTH_FILE=/app/oauth-authorization.json
      - DATA_DIR=/app/data